export const FETCH_TOPICS_DONE = 'FETCH_TOPICS_DONE';
export const FETCH_TOPIC_DONE = 'FETCH_TOPIC_DONE';
export const FETCH_MORE_TOPICS_DONE = 'FETCH_MORE_TOPICS_DONE';
export const SET_TOPIC_TAB = 'SET_TOPIC_TAB';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_SCROLL_TOP = 'SET_SCROLL_TOP';
export const PUSH_BACK_ROUTE = 'PUSH_BACK_ROUTE';
export const POP_BACK_ROUTE = 'POP_BACK_ROUTE';