export const FETCH_TOPICS_DONE = 'FETCH_TOPICS_DONE';
export const FETCH_MORE_TOPICS_DONE = 'FETCH_MORE_TOPICS_DONE';
export const SET_TOPIC_TAB = 'SET_TOPIC_TAB';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';